/**
 * Swagger Petstore - OpenAPI 3.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { PetController } from '../src';
import { testClient } from './testClient.js';
import { expectHeadersToMatch, makeApiCall } from './testHelper.js';

describe('PetController', () => {
  let controller : PetController;

  beforeAll(() => {
    controller = new PetController(testClient);
  });

  it('should Test findPetsByStatus', async () => {
    const response = await makeApiCall(
      () => controller.findPetsByStatus(undefined)
    );

    expect(response.statusCode).toBe(200);

    const expectedHeaders = { 'Content-Type': ['application/json', true] };

    expectHeadersToMatch(response.headers, expectedHeaders);
  });

  it('should Test findPetsByStatus1', async () => {
    const response = await makeApiCall(
      () => controller.findPetsByStatus(undefined)
    );

    expect(response.statusCode).toBe(200);

    const expectedHeaders = { 'Content-Type': ['application/xml', true] };

    expectHeadersToMatch(response.headers, expectedHeaders);
  });

  it('should Test findPetsByTags', async () => {
    const response = await makeApiCall(
      () => controller.findPetsByTags(undefined)
    );

    expect(response.statusCode).toBe(200);

    const expectedHeaders = { 'Content-Type': ['application/json', true] };

    expectHeadersToMatch(response.headers, expectedHeaders);
  });

  it('should Test findPetsByTags1', async () => {
    const response = await makeApiCall(
      () => controller.findPetsByTags(undefined)
    );

    expect(response.statusCode).toBe(200);

    const expectedHeaders = { 'Content-Type': ['application/xml', true] };

    expectHeadersToMatch(response.headers, expectedHeaders);
  });

  it('should Test getPetById', async () => {
    const petId = BigInt(10);

    const response = await makeApiCall(() => controller.getPetById(petId));

    expect(response.statusCode).toBe(200);

    const expectedHeaders = { 'Content-Type': ['application/json', true] };

    expectHeadersToMatch(response.headers, expectedHeaders);
  });

  it('should Test getPetById1', async () => {
    const petId = BigInt(10);

    const response = await makeApiCall(() => controller.getPetById(petId));

    expect(response.statusCode).toBe(200);

    const expectedHeaders = { 'Content-Type': ['application/xml', true] };

    expectHeadersToMatch(response.headers, expectedHeaders);
  });

  it('should Test updatePetWithForm', async () => {
    const petId = BigInt(10);

    const response = await makeApiCall(
      () => controller.updatePetWithForm(petId, undefined, undefined)
    );

    expect(response.statusCode).toBe(200);

    const expectedHeaders = { 'Content-Type': ['application/json', true] };

    expectHeadersToMatch(response.headers, expectedHeaders);
  });

  it('should Test updatePetWithForm1', async () => {
    const petId = BigInt(10);

    const response = await makeApiCall(
      () => controller.updatePetWithForm(petId, undefined, undefined)
    );

    expect(response.statusCode).toBe(200);

    const expectedHeaders = { 'Content-Type': ['application/xml', true] };

    expectHeadersToMatch(response.headers, expectedHeaders);
  });

  it('should Test deletePet', async () => {
    const petId = BigInt(10);

    const response = await makeApiCall(
      () => controller.deletePet(petId, undefined)
    );

    expect(response.statusCode).toBe(200);
  });

  it('should Test uploadFile', async () => {
    const petId = BigInt(10);

    const response = await makeApiCall(
      () => controller.uploadFile(petId, undefined, undefined)
    );

    expect(response.statusCode).toBe(200);

    const expectedHeaders = { 'Content-Type': ['application/json', true] };

    expectHeadersToMatch(response.headers, expectedHeaders);
  });
});
