/**
 * Swagger Petstore - OpenAPI 3.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface MApiResponse {
  code?: number;
  type?: string;
  message?: string;
  additionalProperties?: Record<string, unknown>;
}

export const mApiResponseSchema: Schema<MApiResponse> = typedExpandoObject(
  {
    code: ['code', optional(number())],
    type: ['type', optional(string())],
    message: ['message', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
