/**
 * Swagger Petstore - OpenAPI 3.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for OauthScopePetstoreAuth
 */
export enum OauthScopePetstoreAuth {
  Writepets = 'write:pets',
  Readpets = 'read:pets',
}

/**
 * Schema for OauthScopePetstoreAuth
 */
export const oauthScopePetstoreAuthSchema: Schema<OauthScopePetstoreAuth> = stringEnum(
  OauthScopePetstoreAuth
);
