/**
 * Swagger Petstore - OpenAPI 3.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for OrderStatus
 */
export enum OrderStatus {
  Placed = 'placed',
  Approved = 'approved',
  Delivered = 'delivered',
}

/**
 * Schema for OrderStatus
 */
export const orderStatusSchema: Schema<OrderStatus> = stringEnum(OrderStatus);
