/**
 * Swagger Petstore - OpenAPI 3.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  bigint,
  boolean,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { OrderStatus, orderStatusSchema } from './orderStatus.js';

export interface Order {
  id?: bigint;
  petId?: bigint;
  quantity?: number;
  shipDate?: string;
  /** Order Status */
  status?: OrderStatus;
  complete?: boolean;
  additionalProperties?: Record<string, unknown>;
}

export const orderSchema: Schema<Order> = typedExpandoObject(
  {
    id: ['id', optional(bigint())],
    petId: ['petId', optional(bigint())],
    quantity: ['quantity', optional(number())],
    shipDate: ['shipDate', optional(string())],
    status: ['status', optional(orderStatusSchema)],
    complete: ['complete', optional(boolean())],
  },
  'additionalProperties',
  optional(unknown())
);
