/**
 * Swagger Petstore - OpenAPI 3.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  bigint,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Category, categorySchema } from './category.js';
import { PetStatus, petStatusSchema } from './petStatus.js';
import { Tag, tagSchema } from './tag.js';

export interface Pet {
  id?: bigint;
  name: string;
  category?: Category;
  photoUrls: string[];
  tags?: Tag[];
  /** pet status in the store */
  status?: PetStatus;
  additionalProperties?: Record<string, unknown>;
}

export const petSchema: Schema<Pet> = lazy(() =>
  typedExpandoObject(
    {
      id: ['id', optional(bigint())],
      name: ['name', string()],
      category: ['category', optional(categorySchema)],
      photoUrls: ['photoUrls', array(string(), { xmlItemName: 'photoUrl' })],
      tags: ['tags', optional(array(tagSchema, { xmlItemName: 'tag' }))],
      status: ['status', optional(petStatusSchema)],
    },
    'additionalProperties',
    optional(unknown())
  )
);
