/**
 * Swagger Petstore - OpenAPI 3.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  bigint,
  lazy,
  object,
  optional,
  Schema,
  string,
} from '../schema.js';
import { Category, categorySchema } from './category.js';
import { PetStatusEnum, petStatusEnumSchema } from './petStatusEnum.js';
import { Tag, tagSchema } from './tag.js';

export interface Pet {
  id?: bigint;
  name: string;
  category?: Category;
  photoUrls: string[];
  tags?: Tag[];
  /** pet status in the store */
  status?: PetStatusEnum;
}

export const petSchema: Schema<Pet> = lazy(() =>
  object({
    id: ['id', optional(bigint())],
    name: ['name', string()],
    category: ['category', optional(categorySchema)],
    photoUrls: ['photoUrls', array(string(), { xmlItemName: 'photoUrl' })],
    tags: ['tags', optional(array(tagSchema, { xmlItemName: 'tag' }))],
    status: ['status', optional(petStatusEnumSchema)],
  })
);
