/**
 * Swagger Petstore - OpenAPI 3.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  bigint,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Tag {
  id?: bigint;
  name?: string;
  additionalProperties?: Record<string, unknown>;
}

export const tagSchema: Schema<Tag> = typedExpandoObject(
  { id: ['id', optional(bigint())], name: ['name', optional(string())] },
  'additionalProperties',
  optional(unknown())
);
